language: android

android:
  components:
  - android-24
  - tools
  - build-tools-24.0.2
  - platform-tools
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-24

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
